services:
  coding_test_debug:
    image: coding_test
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/codingTest
